#include "touch_changed.h"

const u8t NIMBUS_EVENT_TOUCH_BEGAN_ID = 3;
const u8t NIMBUS_EVENT_TOUCH_MOVED_ID = 4;
const u8t NIMBUS_EVENT_TOUCH_ENDED_ID = 5;
const u8t NIMBUS_EVENT_TOUCH_STATIONARY_ID = 6;
