require_relative 'buildscript/builder'

application = 'engine'

builder = Builder.new application, ['core/include', 'tyranscript/include', 'engine/include', 'core/include']

task :default => application
